version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - './server/.env'
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/src/db/init:/docker-entrypoint-initdb.d
  backend:
    build: ./server
    env_file:
      - ./server/.env
    # environment:
    #   - PG_HOST=${PG_HOST}
    #   - PG_USER=${PG_USER}
    #   - PG_PASS=${PG_PASS}
    #   - PG_PORT=${PG_PORT}
    #   - PG_DB=${PG_DB}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
volumes:
  pg_data: